/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AiCompareRouteImport } from './routes/ai-compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiskIdRouteImport } from './routes/risk.$id'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCompareRoute = AiCompareRouteImport.update({
  id: '/ai-compare',
  path: '/ai-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIdRoute = RiskIdRouteImport.update({
  id: '/risk/$id',
  path: '/risk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-compare': typeof AiCompareRoute
  '/login': typeof LoginRoute
  '/risk-map': typeof RiskMapRoute
  '/submissions': typeof SubmissionsRoute
  '/risk/$id': typeof RiskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-compare': typeof AiCompareRoute
  '/login': typeof LoginRoute
  '/risk-map': typeof RiskMapRoute
  '/submissions': typeof SubmissionsRoute
  '/risk/$id': typeof RiskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-compare': typeof AiCompareRoute
  '/login': typeof LoginRoute
  '/risk-map': typeof RiskMapRoute
  '/submissions': typeof SubmissionsRoute
  '/risk/$id': typeof RiskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-compare'
    | '/login'
    | '/risk-map'
    | '/submissions'
    | '/risk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-compare'
    | '/login'
    | '/risk-map'
    | '/submissions'
    | '/risk/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-compare'
    | '/login'
    | '/risk-map'
    | '/submissions'
    | '/risk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCompareRoute: typeof AiCompareRoute
  LoginRoute: typeof LoginRoute
  RiskMapRoute: typeof RiskMapRoute
  SubmissionsRoute: typeof SubmissionsRoute
  RiskIdRoute: typeof RiskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-compare': {
      id: '/ai-compare'
      path: '/ai-compare'
      fullPath: '/ai-compare'
      preLoaderRoute: typeof AiCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/$id': {
      id: '/risk/$id'
      path: '/risk/$id'
      fullPath: '/risk/$id'
      preLoaderRoute: typeof RiskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCompareRoute: AiCompareRoute,
  LoginRoute: LoginRoute,
  RiskMapRoute: RiskMapRoute,
  SubmissionsRoute: SubmissionsRoute,
  RiskIdRoute: RiskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
