apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pnc-frontend-secrets
  namespace: pnc
spec:
  provider: azure
  parameters:
    objects: |
      - objectName: "stg/pnc360"   
        objectType: "secretsmanager"
        objectAlias: pnc-secrets
