apiVersion: v1
kind: ServiceAccount
metadata:
  name: pnc-sa
  namespace: pnc
  annotations:
    # AWS IAM role for service account annotation
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/stg-pnc360-role
