apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pnc-frontend-secrets
  namespace: pnc
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "f83747ef-a1b3-4d3a-9db8-32887c4787b9"
    keyvaultName: "pnc360-qa"
    cloudName: "AzurePublicCloud"

    objects: |
      array:
        - |
          objectName: VITE-API-BASE-URL
          objectType: secret
        - |
          objectName: VITE-APP-ENV
          objectType: secret
        - |
          objectName: VITE-GOOGLE-MAPS-API-KEY
          objectType: secret

    tenantId: "e2779e10-54e2-4fab-b08e-00ea2de9bae7"
